<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text31_text31</name>
   <tag></tag>
   <elementGuidId>82833ef6-6010-4b6e-b77f-a3199a7cf860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text31</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4378b14-e8bb-4ccc-9e7a-76aa9401160c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>564352b1-bece-4ff7-99ec-94d5d5521c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text31</value>
      <webElementGuid>ce8d3eeb-be4d-4ffc-96b6-cf56ce72fb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text31&quot;)</value>
      <webElementGuid>6ca0913f-8d3b-423d-a93a-f460ea711a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text31']</value>
      <webElementGuid>e44b83aa-6e2d-4bd6-ac9b-bc4d5eee0559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[31]</value>
      <webElementGuid>3bdcff39-83a5-41c0-b585-52cd70184aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text31']</value>
      <webElementGuid>36d411de-d38e-4f5a-9635-2c97aa16c6a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
