<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text35_text35</name>
   <tag></tag>
   <elementGuidId>eb7a974c-c816-485d-9a5d-4f1c5fcdbea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb5a3537-f247-4b3b-9a2a-4dc4a61a5e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fff6fb1f-cd3b-4b61-bc3b-4838c536087f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text35</value>
      <webElementGuid>819d21cc-eb1d-4c51-87a1-482a20173acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text35&quot;)</value>
      <webElementGuid>cb1c3340-6f64-46db-95ee-47665d406966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text35']</value>
      <webElementGuid>dba0b289-3844-446e-a469-531bec9e6250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[35]</value>
      <webElementGuid>475124d6-98ae-4604-98c0-18dcf13ff1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text35']</value>
      <webElementGuid>e5e9ddc3-fd1a-4e16-b6d5-7004abb82c59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
