<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text29_text29</name>
   <tag></tag>
   <elementGuidId>9256f2e1-630a-4dcd-8a97-edeafe0ad0d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text29']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text29</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c205dd24-ce09-4503-98bc-c64b5c687327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ff28f98-b2d8-490a-afac-f622e1430664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text29</value>
      <webElementGuid>7e7004aa-8556-4bb9-830a-8cc259c8eeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text29&quot;)</value>
      <webElementGuid>1be4e50b-ce9c-4e55-accb-837fbbf3a34e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text29']</value>
      <webElementGuid>d34c20fd-6ae7-4145-b2cb-db13849c9807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[29]</value>
      <webElementGuid>5ff629c3-4d31-44eb-9eb1-358af1eca442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text29']</value>
      <webElementGuid>f7df3bb7-e16d-4230-8139-d191ab9f8596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
