<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text24_text24</name>
   <tag></tag>
   <elementGuidId>71264de1-ee99-4f54-9be0-932d153f9daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>176a5adb-7bae-4271-8af8-5de1ae5e6803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9f56b40-66a7-40b8-b1d7-37b10b05400b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text24</value>
      <webElementGuid>75f7cdf8-4c57-4937-b40f-e4fea7015b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text24&quot;)</value>
      <webElementGuid>0a56a5b3-83bd-4ee8-ad67-b7023c2bf611</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text24']</value>
      <webElementGuid>15efddb6-57aa-4793-9d48-a38f2cddf4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[24]</value>
      <webElementGuid>589c2e86-5052-4316-a491-db4718732958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text24']</value>
      <webElementGuid>09c30acb-ccb7-4745-8d4c-3160ec11af57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
