<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text12_text12</name>
   <tag></tag>
   <elementGuidId>0647af53-8bc7-4c98-a290-ba8f84a13261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caa616f0-2b79-4dcd-90fa-63dff5fe5554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee8df1f4-3039-4a43-8c65-e15b5bd6813c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text12</value>
      <webElementGuid>c13234d9-032f-465e-a51e-8174b85b5d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text12&quot;)</value>
      <webElementGuid>dbffbb48-5253-44c2-aca9-a0c49aa88693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text12']</value>
      <webElementGuid>73b4ac04-428f-4c9b-858e-5e857bf054d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[12]</value>
      <webElementGuid>fa252b40-15ec-413e-92c7-2604794e0c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text12']</value>
      <webElementGuid>232f6acb-f0ac-473b-bca1-8f2db84d77d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
