<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio4_radio5</name>
   <tag></tag>
   <elementGuidId>4cd7715a-2042-4282-a80d-4e193b5f39a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5ea3f63-e658-469f-a3a9-0cd72063c564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>26e47ff4-8b44-483a-beb5-cf58072bf83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio5</value>
      <webElementGuid>f44530e4-7de0-4c8c-8636-38965b9e505a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio5</value>
      <webElementGuid>ef17bb33-d22b-4a80-ba71-19c0b0655d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio5&quot;)</value>
      <webElementGuid>8a00a976-fa52-40cc-9503-6b30a5840497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio5']</value>
      <webElementGuid>1eca8d53-bb11-4040-a688-4dc4af086b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[25]</value>
      <webElementGuid>0fb27a05-5e77-4cc1-aba0-756e72ae0e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio5']</value>
      <webElementGuid>e4b5d2aa-a8dd-453d-8363-97ebd29e1f55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
