<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio2_radio3</name>
   <tag></tag>
   <elementGuidId>c0cc2453-64f0-41f3-94f2-01a1ace94603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55ff41a2-5c94-4eff-95c8-e20edf5e9079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5a40899c-ef94-4e5e-a01b-550dfca9db8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio3</value>
      <webElementGuid>6c32557d-e4fe-48c3-854b-a9309798cf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio3</value>
      <webElementGuid>b975b1bb-3882-4782-8340-b9047dec1611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio3&quot;)</value>
      <webElementGuid>7aade8e0-81fc-43b4-8ab8-9cde116618f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio3']</value>
      <webElementGuid>537e0382-d57c-43b2-be7b-e022469d456b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[23]</value>
      <webElementGuid>f5b447bd-07a9-4afc-812e-158038c5e4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio3']</value>
      <webElementGuid>eafd4ba8-ccb4-449d-abf3-2a50f2606ac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
